import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Header from '@components/Header'
import Container from '@components/Container'
import Button from '@components/Button/Button'
import styles from '@styles/Home.module.scss'


import products from '@data/product.json'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com"/>
        <link rel="preconnect" href="https://cdn.snipcart.com"/>
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css" />
      </Head>

        <Header/>
      <main>
        <Container>
          <h1>Hyper Bros. Trading Cards</h1>
          <h2>Available Cards</h2>
          <ul className={styles.products}>
            {products.map(product => (
              <li key={product.id}>
                <Image width="864" height="1200" src={product.image} alt={`cart of ${product.title}`}/>
                <h3 className={styles.productTitle}>{product.title}</h3>
                <p className={styles.productPrice}>
                  £{product.price}
                </p>
                <p>
                  <Button
                    className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-price={product.price}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={product.image}
                    data-item-name={product.title}
                    data-item-max-quantity={1}
                  
                  >Add to Cart</Button>
                </p>
            </li>

            ))}
          
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
       @copy Hyper Bros. Trading Cards { new Date().getFullYear()}
      </footer>
      <Script src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"></Script>
<div hidden id="snipcart" data-currency="gbp" data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API}></div>
    </div>
  )
}
